version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./mysql-ssl:/etc/mysql/ssl:ro
    depends_on:
      - app

  app:
    build: .
    volumes:
      - .:/var/www/html
      - ./mysql-ssl:/etc/mysql/ssl:ro
    expose:
      - "9000"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ninja
      DB_USERNAME: root
      DB_PASSWORD: rootpass        # <-- set your root password here!
      DB_SSL_CA: /etc/mysql/ssl/ca.pem
      DB_SSL_MODE: VERIFY_CA

  db:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
      --require_secure_transport=ON
      --ssl-ca=/etc/mysql/ssl/ca.pem
      --ssl-cert=/etc/mysql/ssl/server-cert.pem
      --ssl-key=/etc/mysql/ssl/server-key.pem
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # <-- use a strong root password here
      MYSQL_DATABASE: ninja
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-ssl:/etc/mysql/ssl:ro

volumes:
  mysql-data:
